// AIRPORTS DATA
export const airports = [
  { id: "TBC", name: "Tbilisi", city: "Tbilisi" },
  { id: "HND", name: "Hokaido", city: "Hokaido" },
  { id: "KUT", name: "Kutaisi", city: "Kutaisi" },
  { id: "LAX", name: "Los Angeles", city: "Los Angeles" },
  { id: "ORD", name: "O Hare", city: "O Hare" },
  { id: "FRA", name: "Frankfurt ", city: "Frankfurt" },
  { id: "LHR", name: "Heathrow", city: "Heathrow" },
  { id: "AMS", name: "Schiphol", city: "Schiphol" },
  { id: "MAD", name: "Adolfo Suárez Madrid–Barajas", city: "Madrid" },
  { id: "IST", name: "Istanbul ", city: "Istanbul" },
  { id: "BCN", name: "Josep Tarradellas Barcelona–El Prat", city: "Barcelona" },
  { id: "BVD", name: "Bavendam ", city: "Bavendam" },
  { id: "CSP", name: "Caspia City ", city: "Caspia" },
  { id: "DRF", name: "Drefus ", city: "Drefus" },
  { id: "ELN", name: "Elenski ", city: "Elenski" },
  { id: "FRG", name: "Froberg International Airport ", city: "Froberg" },
  { id: "GRN", name: "Graniton ", city: "Graniton" },
  { id: "HSL", name: "Helsar Regional Airport", city: "Helsar" },
  { id: "ISC", name: "Istel City Airport", city: "Istel" },
];

export const months = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];
