// AIRPORTS DATA
export const airports = [
  { id: "TBC", name: "Tbilisi", city: "Tbilisi" },
  { id: "HND", name: "Hokaido", city: "Hokaido" },
  { id: "KUT", name: "Kutaisi", city: "Kutaisi" },
  { id: "LAX", name: "Los Angeles", city: "Los Angeles" },
  { id: "ORD", name: "O Hare", city: "O Hare" },
  { id: "FRA", name: "Frankfurt ", city: "Frankfurt" },
  { id: "LHR", name: "Heathrow", city: "Heathrow" },
  { id: "AMS", name: "Schiphol", city: "Schiphol" },
  { id: "MAD", name: "Madrid", city: "Madrid" },
  { id: "IST", name: "Istanbul ", city: "Istanbul" },
  { id: "BCN", name: "Josep Tarradellas Barcelona–El Prat", city: "Barcelona" },
  { id: "BVD", name: "Bavendam ", city: "Bavendam" },
  { id: "CSP", name: "Caspia City ", city: "Caspia" },
  { id: "DRF", name: "Drefus ", city: "Drefus" },
  { id: "ELN", name: "Elenski ", city: "Elenski" },
  { id: "FRG", name: "Froberg", city: "Froberg" },
  { id: "GRN", name: "Graniton ", city: "Graniton" },
  { id: "HSL", name: "Helsar Regional", city: "Helsar" },
  { id: "ISC", name: "Istel City", city: "Istel" },
];

export const months = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

export const flightsData = [
  {
    id: 1,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 400,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 2,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-07",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 350,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 3,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-08",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 600,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 4,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-09",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 700,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 5,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-10",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 80,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 6,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-11",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 450,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 7,
    from: "Hokaido",
    to: "Tbilisi",
    departure: "2024-04-20",
    return: "2024-04-12",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 650,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 8,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-13",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 750,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 9,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-14",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 850,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 10,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-15",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 500,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 11,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-16",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 750,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 12,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 850,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 13,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 970,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 14,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-19",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 550,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 15,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-20",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 450,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 16,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-21",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 720,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 17,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-22",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 880,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 18,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-23",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 950,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 19,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-24",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 490,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 20,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 470,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 21,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-26",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 780,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 22,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 870,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 23,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 990,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 24,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 570,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 25,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-30",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 460,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 26,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-01",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 730,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 27,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-02",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 890,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 28,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-03",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 960,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 29,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-04",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 490,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 30,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-05",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 480,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },

  {
    id: 31,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 850,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 32,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-26",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 950,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 33,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 1050,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 34,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 650,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 35,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 550,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },

  {
    id: 36,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-30",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 900,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 37,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-01",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 1000,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 38,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-02",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 1100,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 39,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-03",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 700,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 40,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-04",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 600,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 41,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-16",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 440,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 42,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 590,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 43,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 730,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 44,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-19",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 880,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 45,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-20",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 450,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 46,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-21",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 610,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 47,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-22",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 750,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 48,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-23",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 900,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 49,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-24",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 460,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 50,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 630,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 51,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-26",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 770,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 52,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 920,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 53,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 470,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 54,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 650,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 55,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-30",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 790,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 56,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-01",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 940,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 57,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-02",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 480,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 58,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-03",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 670,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 59,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-04",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 810,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 60,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-05",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 960,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 61,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-06",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 490,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 62,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-07",
    way: "Bilateral",
    class: "Economy class",
    transfer: "1",
    transferWay: "departure",
    transferCity: ["TUR"],
    price: 690,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 63,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-08",
    way: "Bilateral",
    class: "Economy class",
    transfer: "1",
    transferWay: "return",
    transferCity: ["TUR"],
    price: 830,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 64,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-09",
    way: "Bilateral",
    class: "Economy class",
    transfer: "1",
    transferWay: "return",
    transferCity: ["TUR"],
    price: 980,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 65,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-10",
    way: "Bilateral",
    class: "Economy class",
    transfer: "1",
    transferWay: "return",
    transferCity: ["TUR"],
    price: 500,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 66,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-11",
    way: "Bilateral",
    class: "Economy class",
    transfer: "1",
    transferWay: "return",
    transferCity: ["TUR"],
    price: 710,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 67,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-12",
    way: "Bilateral",
    class: "Economy class",
    transfer: "1",
    transferWay: "return",
    transferCity: ["TUR"],
    price: 850,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 68,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-13",
    way: "Bilateral",
    class: "Economy class",
    transfer: "1",
    transferWay: "return",
    transferCity: ["TUR"],
    price: 1000,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 69,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-14",
    way: "Bilateral",
    class: "Economy class",
    transfer: "1",
    transferWay: "return",
    transferCity: ["TUR"],
    price: 510,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 70,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-15",
    way: "Bilateral",
    class: "Economy class",
    transfer: "1",
    transferWay: "return",
    transferCity: ["TUR"],
    price: 730,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 71,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-16",
    way: "Bilateral",
    class: "Economy class",
    transfer: "1",
    transferWay: "return",
    transferCity: ["TUR"],
    price: 870,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 72,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "1",
    transferWay: "return",
    transferCity: ["TUR"],
    price: 1020,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 73,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "1",
    transferWay: "return",
    transferCity: ["TUR"],
    price: 520,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 74,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-19",
    way: "Bilateral",
    class: "Economy class",
    transfer: "1",
    transferWay: "return",
    transferCity: ["TUR"],
    price: 750,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 75,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-20",
    way: "Bilateral",
    class: "Economy class",
    transfer: "1",
    transferWay: "return",
    transferCity: ["AMS"],
    price: 890,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 76,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-21",
    way: "Bilateral",
    class: "Economy class",
    transfer: "1",
    transferWay: "return",
    transferCity: ["AMS"],
    price: 1040,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 77,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-22",
    way: "Bilateral",
    class: "Economy class",
    transfer: "1",
    transferWay: "return",
    transferCity: ["AMS"],
    price: 530,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 78,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-23",
    way: "Bilateral",
    class: "Economy class",
    transfer: "1",
    transferWay: "return",
    transferCity: ["AMS"],
    price: 770,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 79,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-24",
    way: "Bilateral",
    class: "Economy class",
    transfer: "1",
    transferWay: "return",
    transferCity: ["AMS"],
    price: 910,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 80,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "1",
    transferWay: "return",
    transferCity: ["AMS"],
    price: 1080,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 81,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-26",
    way: "Bilateral",
    class: "Economy class",
    transfer: "1",
    transferWay: "return",
    transferCity: ["AMS"],
    price: 540,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 82,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "1",
    transferWay: "return",
    transferCity: ["AMS"],
    price: 790,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 83,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "1",
    transferWay: "return",
    transferCity: ["AMS"],
    price: 940,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 84,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "1",
    transferWay: "return",
    transferCity: ["AMS"],
    price: 1110,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 85,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-30",
    way: "Bilateral",
    class: "Economy class",
    transfer: "1",
    transferWay: "return",
    transferCity: ["AMS"],
    price: 550,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 86,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-31",
    way: "Bilateral",
    class: "Economy class",
    transfer: "1",
    transferWay: "return",
    transferCity: ["AMS"],
    price: 800,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 87,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-01",
    way: "Bilateral",
    class: "Economy class",
    transfer: "1",
    transferWay: "return",
    transferCity: ["AMS"],
    price: 950,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 88,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-02",
    way: "Bilateral",
    class: "Economy class",
    transfer: "1",
    transferWay: "return",
    transferCity: ["AMS"],
    price: 1120,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 89,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-03",
    way: "Bilateral",
    class: "Economy class",
    transfer: "1",
    transferWay: "return",
    transferCity: ["AMS"],
    price: 570,
    airlines: {
      departure: "Pegasus",
      return: "Turkish Airlines",
    },
  },
  {
    id: 90,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-04",
    way: "Bilateral",
    class: "Economy class",
    transfer: "1",
    transferWay: "return",
    transferCity: ["AMS"],
    price: 820,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 91,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-10",
    way: "Bilateral",
    class: "Economy class",
    transfer: "1",
    transferWay: "return",
    transferCity: ["AMS"],
    price: 950,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 92,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-11",
    way: "Bilateral",
    transfer: "1",
    transferWay: "return",
    transferCity: ["AMS"],
    price: 450,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 93,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-12",
    way: "Bilateral",
    class: "Economy class",
    transfer: "1",
    transferWay: "return",
    transferCity: ["AMS"],
    price: 1300,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 94,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-13",
    way: "Bilateral",
    class: "Economy class",
    transfer: "1",
    transferWay: "return",
    transferCity: ["TUR"],
    price: 850,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 95,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-14",
    way: "Bilateral",
    class: "Economy class",
    transfer: "1",
    transferWay: "return",
    transferCity: ["TUR"],
    price: 1100,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 96,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-15",
    way: "Bilateral",
    class: "Economy class",
    transfer: "1",
    transferWay: "return",
    transferCity: ["TUR"],
    price: 1500,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 97,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-16",
    way: "Bilateral",
    class: "Economy class",
    transfer: "1",
    transferWay: "return",
    transferCity: ["TUR"],
    price: 800,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 98,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "1",
    transferWay: "return",
    transferCity: ["TUR"],
    price: 950,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 99,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "1",
    transferWay: "return",
    transferCity: ["TUR"],
    price: 1100,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 100,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-19",
    way: "Bilateral",
    class: "Economy class",
    transfer: "1",
    transferWay: "return",
    transferCity: ["TUR"],
    price: 1500,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 101,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-20",
    way: "Bilateral",
    class: "Economy class",
    transfer: "1",
    transferWay: "departure",
    transferCity: ["TUR"],
    price: 800,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 102,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-21",
    way: "Bilateral",
    class: "Economy class",
    transfer: "1",
    transferWay: "departure",
    transferCity: ["TUR"],
    price: 950,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 103,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-22",
    way: "Bilateral",
    class: "Economy class",
    transfer: "1",
    transferWay: "departure",
    transferCity: ["TUR"],
    price: 1100,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 104,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-23",
    way: "Bilateral",
    class: "Economy class",
    transfer: "1",
    transferWay: "departure",
    transferCity: ["TUR"],
    price: 1500,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 105,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-24",
    way: "Bilateral",
    class: "Economy class",
    transfer: "1",
    transferWay: "departure",
    transferCity: ["TUR"],
    price: 800,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 106,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "1",
    transferWay: "departure",
    transferCity: ["TUR"],
    price: 950,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 107,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-26",
    way: "Bilateral",
    class: "Economy class",
    transfer: "1",
    transferWay: "departure",
    transferCity: ["TUR"],
    price: 1100,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 108,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "1",
    transferWay: "departure",
    transferCity: ["TUR"],
    price: 1500,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 109,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "1",
    transferWay: "departure",
    transferCity: ["TUR"],
    price: 800,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 110,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "1",
    transferWay: "departure",
    transferCity: ["TUR"],
    price: 950,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 111,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-30",
    way: "Bilateral",
    class: "Economy class",
    transfer: "1",
    transferWay: "departure",
    transferCity: ["TUR"],
    price: 1100,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 112,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-01",
    way: "Bilateral",
    class: "Economy class",
    transfer: "1",
    transferWay: "departure",
    transferCity: ["TUR"],
    price: 1500,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 113,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-02",
    way: "Bilateral",
    class: "Economy class",
    transfer: "1",
    transferWay: "departure",
    transferCity: ["TUR"],
    price: 800,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 114,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-03",
    way: "Bilateral",
    class: "Economy class",
    transfer: "1",
    transferWay: "departure",
    transferCity: ["TUR"],
    price: 950,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 115,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-04",
    way: "Bilateral",
    class: "Economy class",
    transfer: "1",
    transferWay: "departure",
    transferCity: ["TUR"],
    price: 1100,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 116,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-05",
    way: "Bilateral",
    class: "Economy class",
    transfer: "1",
    transferWay: "departure",
    transferCity: ["TUR"],
    price: 1500,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 117,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-06",
    way: "Bilateral",
    class: "Economy class",
    transfer: "1",
    transferWay: "departure",
    transferCity: ["TUR"],
    price: 800,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 118,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-07",
    way: "Bilateral",
    class: "Economy class",
    transfer: "1",
    transferWay: "departure",
    transferCity: ["TUR"],
    price: 950,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 119,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-08",
    way: "Bilateral",
    class: "Economy class",
    transfer: "1",
    transferWay: "departure",
    transferCity: ["TUR"],
    price: 1100,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 120,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-09",
    way: "Bilateral",
    class: "Economy class",
    transfer: "1",
    transferWay: "departure",
    transferCity: ["TUR"],
    price: 1500,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 121,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-10",
    way: "Bilateral",
    class: "Economy class",
    transfer: "1",
    transferWay: "departure",
    transferCity: ["TUR"],
    price: 800,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 122,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-11",
    way: "Bilateral",
    class: "Economy class",
    transfer: "1",
    transferWay: "departure",
    transferCity: ["TUR"],
    price: 950,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 123,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-12",
    way: "Bilateral",
    class: "Economy class",
    transfer: "1",
    transferWay: "departure",
    transferCity: ["TUR"],
    price: 1100,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 124,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-13",
    way: "Bilateral",
    class: "Economy class",
    transfer: "1",
    transferWay: "departure",
    transferCity: ["TUR"],
    price: 1500,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 125,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-14",
    way: "Bilateral",
    class: "Economy class",
    transfer: "1",
    transferWay: "departure",
    transferCity: ["TUR"],
    price: 800,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 126,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-15",
    way: "Bilateral",
    class: "Economy class",
    transfer: "1",
    transferWay: "departure",
    transferCity: ["TUR"],
    price: 950,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 127,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-16",
    way: "Bilateral",
    class: "Economy class",
    transfer: "1",
    transferWay: "departure",
    transferCity: ["TUR"],
    price: 1100,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 128,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-17",
    way: "Bilateral",
    class: "Economy class",
    transfer: "1",
    transferWay: "departure",
    transferCity: ["TUR"],
    price: 1500,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 129,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "2",
    transferWay: "return",

    transferCity: ["TUR", "BER"],
    price: 800,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 130,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "2",
    transferWay: "return",

    transferCity: ["TUR", "BER"],
    price: 950,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 131,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "2",
    transferWay: "return",
    transferCity: ["TUR", "BER"],
    price: 1100,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 132,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "2",
    transferWay: "return",
    transferCity: ["TUR", "BER"],
    price: 1500,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 133,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "2",
    transferWay: "return",
    transferCity: ["TUR", "BER"],
    price: 800,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 134,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "2",
    transferWay: "departure",
    transferCity: ["TUR", "BER"],
    price: 950,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 135,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "2",
    transferWay: "departure",
    transferCity: ["TUR", "BER"],
    price: 1100,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 136,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "2",
    transferWay: "departure",
    transferCity: ["TUR", "BER"],
    price: 1500,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 137,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "2",
    transferWay: "departure",
    transferCity: ["TUR", "BER"],
    price: 800,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 138,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "2",
    transferWay: "departure",
    transferCity: ["TUR", "BER"],
    price: 950,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 139,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "2",
    transferWay: "departure",
    transferCity: ["TUR", "BER"],
    price: 1100,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 140,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "2",
    transferWay: "departure",
    transferCity: ["SPA", "FRA"],
    price: 1500,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 141,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "2",
    transferWay: "departure",
    transferCity: ["SPA", "FRA"],
    price: 800,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 142,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "2",
    transferWay: "departure",
    transferCity: ["SPA", "FRA"],
    price: 950,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 143,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "2",
    transferWay: "departure",
    transferCity: ["SPA", "FRA"],
    price: 1100,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 144,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "2",
    transferWay: "departure",
    transferCity: ["SPA", "FRA"],
    price: 1500,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 145,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "2",
    transferWay: "departure",
    transferCity: ["SPA", "FRA"],
    price: 800,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 146,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "2",
    transferWay: "departure",
    transferCity: ["SPA", "FRA"],
    price: 950,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 147,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "2",
    transferWay: "departure",
    transferCity: ["SPA", "FRA"],
    price: 1100,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 148,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "2",
    transferWay: "departure",
    transferCity: ["SPA", "FRA"],
    price: 1500,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 149,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "2",
    transferWay: "departure",
    transferCity: ["SPA", "FRA"],
    price: 800,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 150,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "2",
    transferWay: "departure",
    transferCity: ["SPA", "FRA"],
    price: 950,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 151,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "2",
    transferWay: "departure",
    transferCity: ["SPA", "FRA"],
    price: 1100,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 152,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "2",
    transferWay: "departure",
    transferCity: ["SPA", "FRA"],
    price: 1500,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 153,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "2",
    transferWay: "departure",
    transferCity: ["SPA", "FRA"],
    price: 800,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 154,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "2",
    transferWay: "departure",
    transferCity: ["SPA", "FRA"],
    price: 950,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 155,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "2",
    transferWay: "departure",
    transferCity: ["SPA", "FRA"],
    price: 1100,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 156,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "2",
    transferWay: "departure",
    transferCity: ["SPA", "FRA"],
    price: 1500,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 157,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "2",
    transferWay: "return",
    transferCity: ["SPA", "FRA"],
    price: 800,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 158,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "2",
    transferWay: "return",
    transferCity: ["SPA", "FRA"],
    price: 950,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 159,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "2",
    transferWay: "return",
    transferCity: ["SPA", "FRA"],
    price: 1100,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 160,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "2",
    transferWay: "return",
    transferCity: ["SPA", "FRA"],
    price: 1500,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 161,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "2",
    transferWay: "return",
    transferCity: ["SPA", "FRA"],
    price: 800,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 162,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "2",
    transferWay: "return",
    transferCity: ["SPA", "FRA"],
    price: 950,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 163,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "2",
    transferWay: "return",
    transferCity: ["SPA", "FRA"],
    price: 1100,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 164,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "2",
    transferWay: "return",
    transferCity: ["SPA", "FRA"],
    price: 1500,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 165,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "2",
    transferWay: "return",
    transferCity: ["SPA", "FRA"],
    price: 800,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 166,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "2",
    transferWay: "return",
    transferCity: ["TUR", "BER"],
    price: 950,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 167,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "2",
    transferWay: "return",
    transferCity: ["TUR", "BER"],
    price: 1100,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 168,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "2",
    transferWay: "return",
    transferCity: ["TUR", "BER"],
    price: 1500,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 169,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "2",
    transferWay: "return",
    transferCity: ["TUR", "BER"],
    price: 800,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 170,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "2",
    transferWay: "return",
    transferCity: ["TUR", "BER"],
    price: 950,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 171,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "2",
    transferWay: "return",
    transferCity: ["TUR", "BER"],
    price: 1100,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 172,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "2",
    transferWay: "return",
    transferCity: ["TUR", "BER"],
    price: 1500,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 173,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "2",
    transferWay: "return",
    transferCity: ["TUR", "BER"],
    price: 800,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 174,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "2",
    transferWay: "return",
    transferCity: ["TUR", "BER"],
    price: 950,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 175,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "2",
    transferWay: "return",
    transferCity: ["TUR", "BER"],
    price: 1100,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 176,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "2",
    transferWay: "return",
    transferCity: ["TUR", "BER"],
    price: 1500,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 177,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "2",
    transferWay: "return",
    transferCity: ["TUR", "BER"],
    price: 800,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 178,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "2",
    transferWay: "return",
    transferCity: ["TUR", "BER"],
    price: 950,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 179,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "2",
    transferWay: "return",
    transferCity: ["TUR", "BER"],
    price: 1100,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 180,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-07",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 1550,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 181,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-08",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 800,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 182,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-09",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 950,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 183,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-10",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 1100,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 184,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-11",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 1550,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 185,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-12",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 800,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 186,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-13",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 950,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 187,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-14",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 1100,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 188,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-15",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 1530,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 189,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-16",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 800,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 190,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-17",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 950,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 191,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-18",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 1100,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 192,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-19",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 1510,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 193,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-20",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 800,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 194,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-21",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 950,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 195,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-22",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 1100,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 196,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-23",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 1505,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 197,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-24",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 800,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 198,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-25",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 950,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 199,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-26",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 1100,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
  {
    id: 200,
    from: "Tbilisi",
    to: "Hokaido",
    departure: "2024-04-20",
    return: "2024-04-27",
    way: "Bilateral",
    class: "Economy class",
    transfer: "none",
    price: 1590,
    airlines: {
      departure: "Turkish Airlines",
      return: "Pegasus",
    },
  },
];
