// AIRPORTS DATA
export const airports = [
  { id: "TBC", name: "Tbilisi" },
  { id: "HND", name: "Hokaido" },
  { id: "KUT", name: "Kutaisi" },
  { id: "LAX", name: "Los Angeles" },
  { id: "ORD", name: "O Hare" },
  { id: "FRA", name: "Frankfurt Airport" },
  { id: "LHR", name: "Heathrow" },
  { id: "AMS", name: "Schiphol" },
  { id: "MAD", name: "Adolfo Suárez Madrid–Barajas" },
  { id: "FCO", name: "Leonardo da Vinci–Fiumicino" },
  { id: "IST", name: "Istanbul Airport" },
  { id: "BCN", name: "Josep Tarradellas Barcelona–El Prat" },
  { id: "BVD", name: "Bavendam Airport" },
  { id: "CSP", name: "Caspia City Airport" },
  { id: "DRF", name: "Drefus Airport" },
  { id: "ELN", name: "Elenski Airport" },
  { id: "FRG", name: "Froberg International Airport" },
  { id: "GRN", name: "Graniton Airport" },
  { id: "HSL", name: "Helsar Regional Airport" },
  { id: "ISC", name: "Istel City Airport" },
];
